<div class="header-top-area">
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-4 col-md-4 col-sm-12 col-xs-12">
                <div class="logo-area">
                    <a href="<?= $this->url("app");?>" id="logo-head">
                        <?= _APP_NAME_; ?>
                        <?php
                            if($this->vars->menuTitle==true && $this->vars->menuTitle !=null){
                                echo " | ".$this->vars->menuTitle;
                            }; 
                        ?>
                    </a>
                </div>
            </div>
            <div class="col-lg-8 col-md-8 col-sm-12 col-xs-12">
                <div class="header-top-menu">
                    <ul class="nav navbar-nav notika-top-nav">
                        <li class="nav-item">
                            <a
                                href="#"
                                data-toggle="dropdown"
                                role="button"
                                aria-expanded="false"
                                class="nav-link dropdown-toggle">
                                <span>
                                    <i class="notika-icon notika-mail"></i></span>
                                <div class="spinner4 spinner-4"></div>
                                <div class="ntd-ctn">
                                    <span>2</span></div></a>
                                <div role="menu" class="dropdown-menu message-dd chat-dd animated zoomIn">
                                <div class="hd-mg-tt">
                                    <h2>Messages</h2>
                                </div>
                                <div class="hd-message-info">
                                    <a href="#">
                                        <div class="hd-message-sn">
                                            <div class="hd-message-img">
                                                <img src="<?= $this->basePath("/vendor/notika/img/post/1.jpg"); ?>" alt=""/>
                                            </div>
                                            <div class="hd-mg-ctn">
                                                <h3>David Belle</h3>
                                                <p>Cum sociis natoque penatibus et magnis dis parturient montes</p>
                                            </div>
                                        </div>
                                    </a>
                                    <a href="#">
                                        <div class="hd-message-sn">
                                            <div class="hd-message-img">
                                                <img src="<?= $this->basePath("/vendor/notika/img/post/2.jpg"); ?>" alt=""/>
                                            </div>
                                            <div class="hd-mg-ctn">
                                                <h3>Jonathan Morris</h3>
                                                <p>Cum sociis natoque penatibus et magnis dis parturient montes</p>
                                            </div>
                                        </div>
                                    </a>
                                    <a href="#">
                                        <div class="hd-message-sn">
                                            <div class="hd-message-img">
                                                <img src="<?= $this->basePath("/vendor/notika/img/post/4.jpg"); ?>" alt=""/>
                                            </div>
                                            <div class="hd-mg-ctn">
                                                <h3>Fredric Mitchell</h3>
                                                <p>Cum sociis natoque penatibus et magnis dis parturient montes</p>
                                            </div>
                                        </div>
                                    </a>
                                    <a href="#">
                                        <div class="hd-message-sn">
                                            <div class="hd-message-img">
                                                <img src="<?= $this->basePath("/vendor/notika/img/post/1.jpg"); ?>" alt=""/>
                                            </div>
                                            <div class="hd-mg-ctn">
                                                <h3>David Belle</h3>
                                                <p>Cum sociis natoque penatibus et magnis dis parturient montes</p>
                                            </div>
                                        </div>
                                    </a>
                                    <a href="#">
                                        <div class="hd-message-sn">
                                            <div class="hd-message-img">
                                                <img src="<?= $this->basePath("/vendor/notika/img/post/2.jpg"); ?>" alt=""/>
                                            </div>
                                            <div class="hd-mg-ctn">
                                                <h3>Glenn Jecobs</h3>
                                                <p>Cum sociis natoque penatibus et magnis dis parturient montes</p>
                                            </div>
                                        </div>
                                    </a>
                                </div>
                                <div class="hd-mg-va">
                                    <a href="#">View All</a>
                                </div>
                            </div>
                        </li>
                        <li class="nav-item">
                            <a
                                href="#"
                                data-toggle="dropdown"
                                role="button"
                                aria-expanded="false"
                                class="nav-link dropdown-toggle">
                                <span>
                                    <i class="notika-icon notika-alarm"></i>
                                </span>
                                <div class="spinner4 spinner-4"></div>
                                <div class="ntd-ctn">
                                    <span>3</span></div>
                            </a>
                            <div role="menu" class="dropdown-menu message-dd chat-dd animated zoomIn">
                                <div class="hd-mg-tt">
                                    <h2>Notification</h2>
                                </div>
                                <div class="hd-message-info">
                                    <a href="#">
                                        <div class="hd-message-sn">
                                            <div class="hd-message-img">
                                                <img src="<?= $this->basePath("/vendor/notika/img/post/1.jpg"); ?>" alt=""/>
                                            </div>
                                            <div class="hd-mg-ctn">
                                                <h3>David Belle</h3>
                                                <p>Cum sociis natoque penatibus et magnis dis parturient montes</p>
                                            </div>
                                        </div>
                                    </a>
                                    <a href="#">
                                        <div class="hd-message-sn">
                                            <div class="hd-message-img">
                                                <img src="<?= $this->basePath("/vendor/notika/img/post/2.jpg"); ?>" alt=""/>
                                            </div>
                                            <div class="hd-mg-ctn">
                                                <h3>Jonathan Morris</h3>
                                                <p>Cum sociis natoque penatibus et magnis dis parturient montes</p>
                                            </div>
                                        </div>
                                    </a>
                                    <a href="#">
                                        <div class="hd-message-sn">
                                            <div class="hd-message-img">
                                                <img src="<?= $this->basePath("/vendor/notika/img/post/4.jpg"); ?>" alt=""/>
                                            </div>
                                            <div class="hd-mg-ctn">
                                                <h3>Fredric Mitchell</h3>
                                                <p>Cum sociis natoque penatibus et magnis dis parturient montes</p>
                                            </div>
                                        </div>
                                    </a>
                                    <a href="#">
                                        <div class="hd-message-sn">
                                            <div class="hd-message-img">
                                                <img src="<?= $this->basePath("/vendor/notika/img/post/1.jpg"); ?>" alt=""/>
                                            </div>
                                            <div class="hd-mg-ctn">
                                                <h3>David Belle</h3>
                                                <p>Cum sociis natoque penatibus et magnis dis parturient montes</p>
                                            </div>
                                        </div>
                                    </a>
                                    <a href="#">
                                        <div class="hd-message-sn">
                                            <div class="hd-message-img">
                                                <img src="<?= $this->basePath("/vendor/notika/img/post/2.jpg"); ?>" alt=""/>
                                            </div>
                                            <div class="hd-mg-ctn">
                                                <h3>Glenn Jecobs</h3>
                                                <p>Cum sociis natoque penatibus et magnis dis parturient montes</p>
                                            </div>
                                        </div>
                                    </a>
                                </div>
                                <div class="hd-mg-va">
                                    <a href="#">View All</a>
                                </div>
                            </div>
                        </li>
                        <li class="nav-item">
                            <a
                                href="<?= $this->url("app/auth",["action"=>"logout"]);?>"
                                role="button"
                                aria-expanded="false"
                                class="nav-link">
                                <strong><span>
                                    <i class="fa fa-sign-out"></i>
                                </span></strong>
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>