<?php
// use Zend\Mvc\Application;
use Zend\Debug\Debug;
// Debug::dump($this->identity());die();
$this->headLink()->appendStylesheet('https://fonts.googleapis.com/css?family=Inconsolata');
$this->headStyle()->captureStart();
?>
html {
  min-height: 100%;
}

body {
  box-sizing: border-box;
  height: 100%;
  background-color: #000000;
  background-image: radial-gradient(#11581E, #041607);
  font-family: 'Inconsolata', Helvetica, sans-serif;
  font-size: 1.5rem;
  color: rgba(128, 255, 128, 0.8);
  text-shadow:
      0 0 1ex rgba(51, 255, 51, 1),
      0 0 2px rgba(255, 255, 255, 0.8);
}

.overlay {
  pointer-events: none;
  position: absolute;
  width: 100%;
  height: 100%;
  background:
      repeating-linear-gradient(
      180deg,
      rgba(0, 0, 0, 0) 0,
      rgba(0, 0, 0, 0.3) 50%,
      rgba(0, 0, 0, 0) 100%);
  background-size: auto 4px;
  z-index: 99;
}

.overlay::before {
  content: "";
  pointer-events: none;
  position: absolute;
  display: block;
  top: 0;
  left: 0;
  right: 0;
  bottom: 0;
  width: 100%;
  height: 100%;
  background-image: linear-gradient(
      0deg,
      transparent 0%,
      rgba(32, 128, 32, 0.2) 2%,
      rgba(32, 128, 32, 0.8) 3%,
      rgba(32, 128, 32, 0.2) 3%,
      transparent 100%);
  background-repeat: no-repeat;
  animation: scan 7.5s linear 0s infinite;
}

@keyframes scan {
  0%        { background-position: 0 -100vh; }
  35%, 100% { background-position: 0 100vh; }
}

.terminal {
  box-sizing: inherit;
  position: absolute;
  height: 100%;
  width: 1000px;
  max-width: 100%;
  padding: 4rem;
}

.output {
  color: rgba(128, 255, 128, 0.8);
  text-shadow:
      0 0 1px rgba(51, 255, 51, 0.4),
      0 0 2px rgba(255, 255, 255, 0.8);
}

.output.stacktrace{
  font-size: 1rem;
}

.output::before {
  content: "> ";
}

a {
  color: #fff;
  text-decoration: none;
}

a::before {
  content: "[";
}

a::after {
  content: "]";
}

.errorcode {
  color: white;
}
<?php
$this->headStyle()->captureEnd();
$identity = $this->identity();
// Debug::dump($this->display_exceptions);die();
// Debug::dump($this->exception->getFile());
// Debug::dump($this->exception->getMessage());
// die();
$pos1 = strpos($this->exception->getMessage(), 'Session validation failed');
$pos2 = strpos($this->exception->getMessage(), 'Zend\Authentication\AuthenticationService');
if($pos1 !== false && $pos2 !== false){
  session_unset();
  header("Refresh:0");
  // Debug::dump($this->url());
  // $this->_redirect('/admin/track/index');
  // $this->_redirect('front/auth', ['action'=>'logout']);
  // die("REDIRECT");
  die();
}
?>

<div class="overlay"></div>
<div class="terminal">
  <h1><span class="errorcode">An error occurred</span></h1>
<?php 
// Debug::dump($identity);die();
if(_DEBUG_ || ($identity!=null && isset($identity['roles'][1]))){
// Debug::dump($this->display_exceptions);die();
?>
<?php if (! empty($this->display_exceptions)) : ?>
    <?php if (isset($this->exception)
        && ($this->exception instanceof \Exception || $this->exception instanceof \Error)) : ?>
  <h2><span class="errorcode">Additional information : </span><?= get_class($this->exception) ?></h2>
  <p class="output">
    File : <?= $this->exception->getFile() ?>:<?= $this->exception->getLine() ?>
    </p>
  <p class="output">
    Message : <?= $this->escapeHtml($this->exception->getMessage()) ?>
    </p>
  <p class="output stacktrace">
    Stack trace : <?= $this->escapeHtml($this->exception->getTraceAsString()) ?>
    </p>
</dl>

        <?php if ($ex = $this->exception->getPrevious()) : ?>
  <h2><span class="errorcode">Previous exceptions.</span></h2>
            <?php $icount = 0 ?>
            <?php while ($ex) : ?>
  <h2><span class="errorcode"><?= get_class($ex) ?></span></h2>
  <p class="output">
    File : <?= $ex->getFile() ?>:<?= $ex->getLine() ?>
    </p>
  <p class="output">
    Message : <?= $this->escapeHtml($ex->getMessage()) ?>
    </p>
  <p class="output stacktrace">
    Stack trace : <?= $this->escapeHtml($ex->getTraceAsString()) ?>
    </p>
                <?php
                $ex = $ex->getPrevious();
                if (++$icount >= 50) {
                    echo '<h2><span class="errorcode">There may be more exceptions, but we do not have enough memory to process it.</span></h2>';
                    break;
                }
                ?>
            <?php endwhile ?>
</ul>
        <?php endif ?>
    <?php else : ?>
  <h2><span class="errorcode">No Exception available.</span></h2>
    <?php endif ?>
<?php endif ?>
<?php
}
?>

  <p class="output"><a href="<?= $this->identity()['default_redirect'] ?>">BACK</a></p>
</div>