<div class="d-none d-md-block bg-white header-secondary header-submenu pt-7">
    <div class="full-container ">
        <div class="d-flex justify-content-between">
            <div class="d-flex justify-content-start" style="min-width: 15em;">
                <!-- breadcrumb -->
                <ol class="breadcrumb m-0 pt-4">
                    <?php 
                        foreach($this->item as $k=>$v){ 
                    ?>
                        <li class="breadcrumb-item"><?php if($v!="" && $v!="#"){?><a href="<?= $v; ?>"><?= $k; ?></a><?php }else{ echo $k; }?></li>
                    <?php } ?>
                </ol>
                <!-- End breadcrumb -->
            </div>
            <div class="d-flex justify-content-end">
                <h4 class="m-0 pt-2 px-5"><?= $this->subtitle; ?><h4>
            </div>
        </div>
    </div>
</div>