<script>
"use strict";
let tableMenu;
let deleteModal;
let delActive = {};
let showDeleteModal,dismissDeleteModal,deleteMenu,deleteAjax,deleteCSRF;
</script>
<?php
$this->headScript()->captureStart();
?>
"use strict";
(function ($) {
deleteAjax = null;
deleteCSRF = '<?= $this->csrf; ?>';

showDeleteModal = function(id,module,layout,title){
    deleteModal.find("#delModal_mid").html(id);
    deleteModal.find("#delModal_module").html(module);
    deleteModal.find("#delModal_layout").html(layout);
    deleteModal.find("#delModal_title").html(title);
    delActive = {
        mid : id,
        module : module,
        layout : layout,
        title : title,
    };
    deleteModal.modal("show");
}

dismissDeleteModal = function(){
    deleteModal.find("#delModal_mid").html("");
    deleteModal.find("#delModal_module").html("");
    deleteModal.find("#delModal_layout").html("");
    deleteModal.find("#delModal_title").html("");
    delActive = {};
    deleteModal.modal("hide");
}

deleteMenu = function(){
    //console.log(delActive);
    //return false;
    if(deleteAjax!=null)deleteAjax.abort();
    showLoader();
    deleteAjax = $.ajax({
        url : "<?= $this->url('ajax/data-generator/deleteSQL'); ?>",
        async : true,
        cache : false,
        method : "POST",
        processData : true,
        //contentType : 'json',
        dataType : 'json',
        crossDomain : false,
        timeout : 10000, //milliseconds
        headers : {
            'X-CSRF-TOKEN' : deleteCSRF,
            'X-DB-CONN' : 'db-sys',
            'X-DB-TABLE' : '_menu',
        },
        data : {
            id: delActive.mid
        },
        beforeSend: function( jqXHR, settings ){

        },
        complete: function( jqXHR, textStatus ){
            dismissDeleteModal();
        },
        error: function( jqXHR, textStatus, errorThrown ){
            hideLoader();
            showErrorModal("Menu failed to deleted","REMOVE MENU",5000);
        },
        success: function( data, textStatus, jqXHR ){
            //console.log(data);
            if(data.ret != undefined && data.csrf != undefined && data.ret){
                deleteCSRF = data.csrf;
                tableMenu.find("tr#row_menu_"+delActive.mid).remove();
                hideLoader();
                showNotifModal("Menu has been deleted","REMOVE MENU",2000);
                
                setTimeout(function(){location.reload();},2000);
            }else{
                hideLoader();
                showErrorModal("Menu failed to deleted","REMOVE MENU",5000);
            }
        }
    });
}

$(document).ready(function(){
    tableMenu = $("#table-menu");
    tableMenu.DataTable();

    deleteModal = $("#deleteModal");
});
})(jQuery); 
<?php
$this->headScript()->captureEnd();
?>
<div class="container-fluid">
    <div class="row">
        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
            <div class="data-table-list">
                <div class="basic-tb-hd">
                    <div class="pull-right">
                        <a class="btn bg-default" href="<?= $this->url('admin/manage-menu/add-menu');?>"><i class="fas fa-plus"></i> ADD MENU</a>
                    </div>
                    <h2>Menu List</h2>
                    <p>System Administration</p>
                </div>
                <div class="table-responsive">
                    <table id="table-menu" class="table table-striped table-hover">
                        <thead>
                            <tr>
                            <?php
                            foreach ($this->arr_keys as $k=>$v) {
                            ?>
                                <th data-field="<?= $k; ?>" style="white-space: nowrap;" nowrap><?= $v; ?></th>
                            <?php
                            }
                            ?>
                            </tr>
                        </thead>
                        <tbody>
                            <?php
                            // !d($this->menus,$this->arr_keys);
                            foreach ($this->menus as $k=>$v) {
                            ?>
                            <tr id="row_menu_<?= $v['id']; ?>">
                                <?php
                                foreach ($this->arr_keys as $k2=>$v2) {
                                    // !d($v,$k2);
                                    if($k2===0){
                                ?>
                                    <td data-field="_act_" data-row="<?= $k; ?>" style="white-space: nowrap;" nowrap>
                                        <button data-toggle="tooltip" data-placement="top" data-original-title="Delete Menu" data-id="<?= $v['id']; ?>" data-row="<?= $k; ?>" class="btn btn-xs btn-danger" onclick="showDeleteModal('<?= $v['id']; ?>','<?= $v['module']; ?>','<?= $v['layout']; ?>','<?= $v['title']; ?>')"><i class="fas fa-times"></i> DELETE</button>
                                        <a data-toggle="tooltip" data-placement="top" data-original-title="Edit Menu" data-id="<?= $v['id']; ?>" data-row="<?= $k; ?>" class="btn btn-xs btn-primary" href="<?= $this->url('admin/manage-menu/edit-menu',['mid'=>$v['id']]);?>"><i class="fas fa-edit"></i> EDIT</a>
                                    </td>
                                <?php  
                                    }else{
                                        ?>
                                    <td data-field="<?= $k2; ?>" data-row="<?= $k; ?>" style="white-space: nowrap;" nowrap><?= ($k2==='icon')?'<i class="'.$v[$k2].'"></i> ':''; ?><?= $v[$k2]; ?></td>
                                <?php
                                    }
                                }
                                ?>
                            </tr>
                            <?php
                            }
                            ?>
                        </tbody>
                        <tfoot>
                            <tr>
                            <?php
                            foreach ($this->arr_keys as $k=>$v) {
                            ?>
                                <th data-id="<?= $k; ?>" style="white-space: nowrap;" nowrap><?= $v; ?></th>
                            <?php
                            }
                            ?>
                            </tr>
                        </tfoot>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="modal fade" id="deleteModal" role="dialog">
    <div class="modal-dialog  modal-sm modals-default nk-red">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
            </div>
            <div class="modal-body">
                <h2>DELETE MENU</h2>
                <p>Are you sure to remove this menu?</p>
                <table class="text-white font-weight-bold">
                    <tr>
                        <td>MENU ID</td><td>&nbsp;&nbsp;&nbsp;:&nbsp;&nbsp;&nbsp;</td><td id="delModal_mid"></td>
                    </tr>
                    <tr>
                        <td>Module </td><td>&nbsp;&nbsp;&nbsp;:&nbsp;&nbsp;&nbsp;</td><td id="delModal_module"></td>
                    </tr>
                    <tr>
                        <td>Layout </td><td>&nbsp;&nbsp;&nbsp;:&nbsp;&nbsp;&nbsp;</td><td id="delModal_layout"></td>
                    </tr>
                    <tr>
                        <td>Title </td><td>&nbsp;&nbsp;&nbsp;:&nbsp;&nbsp;&nbsp;</td><td id="delModal_title"></td>
                    </tr>
                </table>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" onclick="deleteMenu()">DELETE</button>
                <button type="button" class="btn btn-default" onclick="dismissDeleteModal()">CANCEL</button>
            </div>
        </div>
    </div>
</div>