<script>
"use strict";
let tableUser;
let deleteModal;
let delActive = {};
let showDeleteModal,dismissDeleteModal,deleteUser,deleteAjax,deleteCSRF;
</script>
<?php
$this->headScript()->captureStart();
?>
"use strict";
(function ($) {
deleteAjax = null;
deleteCSRF = '<?= $this->csrf; ?>';

showDeleteModal = function(id,username,fullname,email){
    deleteModal.find("#delModal_uid").html(id);
    deleteModal.find("#delModal_username").html(username);
    deleteModal.find("#delModal_fullname").html(fullname);
    deleteModal.find("#delModal_email").html(email);
    delActive = {
        uid : id,
        username : username,
        fullname : fullname,
        email : email,
    };
    deleteModal.modal("show");
}

dismissDeleteModal = function(){
    deleteModal.find("#delModal_uid").html("");
    deleteModal.find("#delModal_username").html("");
    deleteModal.find("#delModal_fullname").html("");
    deleteModal.find("#delModal_email").html("");
    delActive = {};
    deleteModal.modal("hide");
}

deleteUser = function(){
    //console.log(delActive);
    //return false;
    if(deleteAjax!=null)deleteAjax.abort();
    showLoader();
    deleteAjax = $.ajax({
        url : "<?= $this->url('ajax/data-generator/deleteSQL'); ?>",
        async : true,
        cache : false,
        method : "POST",
        processData : true,
        //contentType : 'json',
        dataType : 'json',
        crossDomain : false,
        timeout : 10000, //milliseconds
        headers : {
            'X-CSRF-TOKEN' : deleteCSRF,
            'X-DB-CONN' : 'db-sys',
            'X-DB-TABLE' : '_user',
        },
        data : {
            id: delActive.uid
        },
        beforeSend: function( jqXHR, settings ){

        },
        complete: function( jqXHR, textStatus ){
            dismissDeleteModal();
        },
        error: function( jqXHR, textStatus, errorThrown ){
            hideLoader();
            showErrorModal("User failed to deleted","REMOVE USER",5000);
        },
        success: function( data, textStatus, jqXHR ){
            //console.log(data);
            if(data.ret != undefined && data.csrf != undefined && data.ret){
                deleteCSRF = data.csrf;
                tableUser.find("tr#row_user_"+delActive.uid).remove();
                hideLoader();
                showNotifModal("User has been deleted","REMOVE USER",2000);
                
                setTimeout(function(){location.reload();},2000);
            }else{
                hideLoader();
                showErrorModal("User failed to deleted","REMOVE USER",5000);
            }
        }
    });
}

$(document).ready(function(){
    tableUser = $("#table-user");
    tableUser.DataTable();

    deleteModal = $("#deleteModal");
});
})(jQuery); 
<?php
$this->headScript()->captureEnd();
?>
<div class="container-fluid">
    <div class="row">
        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
            <div class="data-table-list">
                <div class="basic-tb-hd">
                    <div class="pull-right">
                        <a class="btn bg-default" href="<?= $this->url('admin/manage-user/add-user');?>"><i class="fas fa-plus"></i> ADD USER</a>
                    </div>
                    <h2>User List</h2>
                    <p>System Administration</p>
                </div>
                <div class="table-responsive">
                    <table id="table-user" class="table table-striped table-hover">
                        <thead>
                            <tr>
                            <?php
                            foreach ($this->arr_keys as $k=>$v) {
                            ?>
                                <th data-field="<?= $k; ?>" style="white-space: nowrap;" nowrap><?= $v; ?></th>
                            <?php
                            }
                            ?>
                            </tr>
                        </thead>
                        <tbody>
                            <?php
                            // !d($this->users,$this->arr_keys);
                            foreach ($this->users as $k=>$v) {
                            ?>
                            <tr id="row_user_<?= $v['id']; ?>">
                                <?php
                                foreach ($this->arr_keys as $k2=>$v2) {
                                    // !d($v,$k2);
                                    if($k2===0){
                                ?>
                                    <td data-field="_act_" data-row="<?= $k; ?>" style="white-space: nowrap;" nowrap>
                                        <button data-toggle="tooltip" data-placement="top" data-original-title="Delete User" data-id="<?= $v['id']; ?>" data-row="<?= $k; ?>" class="btn btn-xs btn-danger" onclick="showDeleteModal('<?= $v['id']; ?>','<?= $v['username']; ?>','<?= $v['full_name']; ?>','<?= $v['email']; ?>')"><i class="fas fa-times"></i> DELETE</button>
                                        <a data-toggle="tooltip" data-placement="top" data-original-title="Edit User" data-id="<?= $v['id']; ?>" data-row="<?= $k; ?>" class="btn btn-xs btn-primary" href="<?= $this->url('admin/manage-user/edit-user',['uid'=>$v['id']]);?>"><i class="fas fa-edit"></i> EDIT</a>
                                    </td>
                                <?php  
                                    }else{
                                        ?>
                                    <td data-field="<?= $k2; ?>" data-row="<?= $k; ?>" style="white-space: nowrap;" nowrap><?= $v[$k2]; ?></td>
                                <?php
                                    }
                                }
                                ?>
                            </tr>
                            <?php
                            }
                            ?>
                        </tbody>
                        <tfoot>
                            <tr>
                            <?php
                            foreach ($this->arr_keys as $k=>$v) {
                            ?>
                                <th data-id="<?= $k; ?>" style="white-space: nowrap;" nowrap><?= $v; ?></th>
                            <?php
                            }
                            ?>
                            </tr>
                        </tfoot>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="modal fade" id="deleteModal" role="dialog">
    <div class="modal-dialog  modal-sm modals-default nk-red">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
            </div>
            <div class="modal-body">
                <h2>DELETE USER</h2>
                <p>Are you sure to remove this user?</p>
                <table class="text-white font-weight-bold">
                    <tr>
                        <td>UID</td><td>&nbsp;&nbsp;&nbsp;:&nbsp;&nbsp;&nbsp;</td><td id="delModal_uid"></td>
                    </tr>
                    <tr>
                        <td>Username </td><td>&nbsp;&nbsp;&nbsp;:&nbsp;&nbsp;&nbsp;</td><td id="delModal_username"></td>
                    </tr>
                    <tr>
                        <td>Fullname </td><td>&nbsp;&nbsp;&nbsp;:&nbsp;&nbsp;&nbsp;</td><td id="delModal_fullname"></td>
                    </tr>
                    <tr>
                        <td>Email </td><td>&nbsp;&nbsp;&nbsp;:&nbsp;&nbsp;&nbsp;</td><td id="delModal_email"></td>
                    </tr>
                </table>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" onclick="deleteUser()">DELETE</button>
                <button type="button" class="btn btn-default" onclick="dismissDeleteModal()">CANCEL</button>
            </div>
        </div>
    </div>
</div>