<script>
"use strict";
let tableRole;
let deleteModal;
let delActive = {};
let showDeleteModal,dismissDeleteModal,deleteRole,deleteAjax,deleteCSRF;
</script>
<?php
$this->headScript()->captureStart();
?>
"use strict";
(function ($) {
deleteAjax = null;
deleteCSRF = '<?= $this->csrf; ?>';

showDeleteModal = function(rolecode,rolename){
    deleteModal.find("#delModal_code").html(rolecode);
    deleteModal.find("#delModal_rolename").html(rolename);
    delActive = {
        code : rolecode,
        rolename : rolename
    };
    deleteModal.modal("show");
}

dismissDeleteModal = function(){
    deleteModal.find("#delModal_code").html("");
    deleteModal.find("#delModal_rolename").html("");
    delActive = {};
    deleteModal.modal("hide");
}

deleteRole = function(){
    //console.log(delActive);
    //return false;
    if(deleteAjax!=null)deleteAjax.abort();
    showLoader();
    deleteAjax = $.ajax({
        url : "<?= $this->url('ajax/data-generator/deleteSQL'); ?>",
        async : true,
        cache : false,
        method : "POST",
        processData : true,
        //contentType : 'json',
        dataType : 'json',
        crossDomain : false,
        timeout : 10000, //milliseconds
        headers : {
            'X-CSRF-TOKEN' : deleteCSRF,
            'X-DB-CONN' : 'db-sys',
            'X-DB-TABLE' : '_role',
        },
        data : {
            code: delActive.code
        },
        beforeSend: function( jqXHR, settings ){

        },
        complete: function( jqXHR, textStatus ){
            dismissDeleteModal();
        },
        error: function( jqXHR, textStatus, errorThrown ){
            hideLoader();
            showErrorModal("Role failed to deleted","REMOVE ROLE",5000);
        },
        success: function( data, textStatus, jqXHR ){
            //console.log(data);
            if(data.ret != undefined && data.csrf != undefined && data.ret){
                deleteCSRF = data.csrf;
                tableRole.find("tr#row_role_"+delActive.code).remove();
                hideLoader();
                showNotifModal("Role has been deleted","REMOVE ROLE",2000);
                setTimeout(function(){location.reload();},2000);
            }else{
                hideLoader();
                showErrorModal("Role failed to deleted","REMOVE ROLE",5000);
            }
        }
    });
}

$(document).ready(function(){
    tableRole = $("#table-role");
    tableRole.DataTable();

    deleteModal = $("#deleteModal");
});
})(jQuery); 
<?php
$this->headScript()->captureEnd();
?>
<div class="container-fluid">
    <div class="row">
        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
            <div class="data-table-list">
                <div class="basic-tb-hd">
                    <div class="pull-right">
                        <a class="btn bg-default" href="<?= $this->url('admin/manage-role/add-role');?>"><i class="fas fa-plus"></i> ADD ROLE</a>
                    </div>
                    <h2>Role List</h2>
                    <p>System Administration</p>
                </div>
                <div class="table-responsive">
                    <table id="table-role" class="table table-striped table-hover">
                        <thead>
                            <tr>
                            <?php
                            foreach ($this->arr_keys as $k=>$v) {
                            ?>
                                <th data-field="<?= $k; ?>" style="white-space: nowrap;" nowrap><?= $v; ?></th>
                            <?php
                            }
                            ?>
                            </tr>
                        </thead>
                        <tbody>
                            <?php
                            // !d($this->roles,$this->arr_keys);
                            foreach ($this->roles as $k=>$v) {
                            ?>
                            <tr id="row_role_<?= $v['code']; ?>">
                                <?php
                                foreach ($this->arr_keys as $k2=>$v2) {
                                    // !d($v,$k2);
                                    if($k2===0){
                                ?>
                                    <td data-field="_act_" data-row="<?= $k; ?>" style="white-space: nowrap;" nowrap>
                                        <button data-toggle="tooltip" data-placement="top" data-original-title="Delete Role" data-code="<?= $v['code']; ?>" data-row="<?= $k; ?>" class="btn btn-xs btn-danger" onclick="showDeleteModal('<?= $v['code']; ?>','<?= $v['name']; ?>')"><i class="fas fa-times"></i> DELETE</button>
                                        <a data-toggle="tooltip" data-placement="top" data-original-title="Edit Role" data-code="<?= $v['code']; ?>" data-row="<?= $k; ?>" class="btn btn-xs btn-primary" href="<?= $this->url('admin/manage-role/edit-role',['code'=>$v['code']]);?>"><i class="fas fa-edit"></i> EDIT</a>
                                    </td>
                                <?php  
                                    }else{
                                        ?>
                                    <td data-field="<?= $k2; ?>" data-row="<?= $k; ?>" style="white-space: nowrap;" nowrap><?= $v[$k2]; ?></td>
                                <?php
                                    }
                                }
                                ?>
                            </tr>
                            <?php
                            }
                            ?>
                        </tbody>
                        <tfoot>
                            <tr>
                            <?php
                            foreach ($this->arr_keys as $k=>$v) {
                            ?>
                                <th data-id="<?= $k; ?>" style="white-space: nowrap;" nowrap><?= $v; ?></th>
                            <?php
                            }
                            ?>
                            </tr>
                        </tfoot>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="modal fade" id="deleteModal" role="dialog">
    <div class="modal-dialog  modal-sm modals-default nk-red">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
            </div>
            <div class="modal-body">
                <h2>DELETE ROLE</h2>
                <p>Are you sure to remove this role?</p>
                <table class="text-white font-weight-bold">
                    <tr>
                        <td>Role Code</td><td>&nbsp;&nbsp;&nbsp;:&nbsp;&nbsp;&nbsp;</td><td id="delModal_code"></td>
                    </tr>
                    <tr>
                        <td>Role Name </td><td>&nbsp;&nbsp;&nbsp;:&nbsp;&nbsp;&nbsp;</td><td id="delModal_rolename"></td>
                    </tr>
                </table>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" onclick="deleteRole()">DELETE</button>
                <button type="button" class="btn btn-default" onclick="dismissDeleteModal()">CANCEL</button>
            </div>
        </div>
    </div>
</div>