<?= $this->doctype() ?>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <?= $this->headTitle()->setAutoEscape(false) ?>
 
        <?= $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0, shrink-to-fit=no"')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?= $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico']); ?>
        <?= $this->headStyle() ?>
    </head>
    <body>
        <?= $this->content ?>

        <!-- Scripts -->
        <?= $this->headScript(); ?>
        <?= $this->inlineScript() ?>
    </body>
</html>
