<!doctype html>
<html class="no-js" lang="">

<head>
    <meta charset="utf-8">
    <?= 
        $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0, shrink-to-fit=no')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge,chrome=1');
    ?>
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <?= $this->headTitle()->setAutoEscape(false) ?>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="Content-Security-Policy" 
      content="script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline'; connect-src 'self';font-src 'self';
      child-src 'self';img-src 'self';media-src 'self';object-src 'self';">
    <!-- favicon
		============================================ -->
    <link rel="shortcut icon" type="image/x-icon" href="<?= $this->basePath("img/favicon.ico"); ?>">
    <!-- Google Fonts
		============================================ -->
    <!-- <link href="https://fonts.googleapis.com/css?family=Roboto:100,300,400,700,900" rel="stylesheet"> -->
    <!-- <link href="<?= $this->basePath("/font/roboto-webfont/roboto.all.css"); ?>" rel="stylesheet"> -->
    <link href="<?= $this->basePath("/font/myfont.css"); ?>" rel="stylesheet">
    <!-- Bootstrap CSS
		============================================ -->
    <link rel="stylesheet" href="<?= $this->basePath("/vendor/notika/css/bootstrap.min.css"); ?>">
    <!-- <link rel="stylesheet" href="<?= $this->basePath("/bower_components/bootstrap4/dist/css/bootstrap.min.css"); ?>"> -->
    <!-- Bootstrap CSS
		============================================ -->
    <!-- <link rel="stylesheet" href="<?= $this->basePath("/vendor/notika/css/font-awesome.min.css"); ?>"> -->
    <link rel="stylesheet" href="<?= $this->basePath("/bower_components/font-awesome/css/all.min.css"); ?>">
    <link rel="stylesheet" href="<?= $this->basePath("/bower_components/wow/css/libs/animate.css"); ?>">
    <!-- owl.carousel CSS
		============================================ -->
    <!-- <link rel="stylesheet" href="<?= $this->basePath("/vendor/notika/css/owl.carousel.css"); ?>"> -->
    <link rel="stylesheet" href="<?= $this->basePath("/bower_components/owl.carousel/dist/assets/owl.carousel.min.css"); ?>">
    <!-- <link rel="stylesheet" href="<?= $this->basePath("/vendor/notika/css/owl.theme.css"); ?>"> -->
    <link rel="stylesheet" href="<?= $this->basePath("/bower_components/owl.carousel/dist/assets/owl.theme.green.min.css"); ?>">
    <link rel="stylesheet" href="<?= $this->basePath("/vendor/notika/css/owl.transitions.css"); ?>">
    <!-- meanmenu CSS
		============================================ -->
    <link rel="stylesheet" href="<?= $this->basePath("/vendor/notika/css/meanmenu/meanmenu.min.css"); ?>">
    <!-- animate CSS
		============================================ -->
    <link rel="stylesheet" href="<?= $this->basePath("/vendor/notika/css/animate.css"); ?>">
    <!-- normalize CSS
		============================================ -->
    <link rel="stylesheet" href="<?= $this->basePath("/vendor/notika/css/normalize.css"); ?>">
    <!-- Data Table JS
		============================================ -->
    <!-- <link rel="stylesheet" href="<?= $this->basePath("/vendor/notika/css/jquery.dataTables.min.css"); ?>"> -->
    <link rel="stylesheet" href="<?= $this->basePath("/bower_components/datatables.net-dt/css/jquery.dataTables.min.css"); ?>">
    <!-- mCustomScrollbar CSS
		============================================ -->
    <link rel="stylesheet" href="<?= $this->basePath("/vendor/notika/css/scrollbar/jquery.mCustomScrollbar.min.css"); ?>">
    <!-- jvectormap CSS
		============================================ -->
    <!-- <link rel="stylesheet" href="<?= $this->basePath("/vendor/notika/css/jvectormap/jquery-jvectormap-2.0.3.css"); ?>"> -->
    <link rel="stylesheet" href="<?= $this->basePath("/bower_components/jvectormap/jquery-jvectormap.css"); ?>">
    <!-- notika icon CSS
		============================================ -->
    <link rel="stylesheet" href="<?= $this->basePath("/vendor/notika/css/notika-custom-icon.css"); ?>">
    <!-- bootstrap select CSS
		============================================ -->
    <link rel="stylesheet" href="<?= $this->basePath("/vendor/notika/css/bootstrap-select/bootstrap-select.css"); ?>">
    <!-- datapicker CSS
		============================================ -->
    <link rel="stylesheet" href="<?= $this->basePath("/vendor/notika/css/datapicker/datepicker3.css"); ?>">
    <!-- Color Picker CSS
		============================================ -->
    <link rel="stylesheet" href="<?= $this->basePath("/vendor/notika/css/color-picker/farbtastic.css"); ?>">
    <!-- main CSS
		============================================ -->
    <link rel="stylesheet" href="<?= $this->basePath("/vendor/notika/css/chosen/chosen.css"); ?>">
    <!-- notification CSS
		============================================ -->
    <link rel="stylesheet" href="<?= $this->basePath("/vendor/notika/css/notification/notification.css"); ?>">
    <!-- dropzone CSS
		============================================ -->
    <link rel="stylesheet" href="<?= $this->basePath("/vendor/notika/css/dropzone/dropzone.css"); ?>">
    <!-- wave CSS
		============================================ -->
    <link rel="stylesheet" href="<?= $this->basePath("/vendor/notika/css/wave/waves.min.css"); ?>">
    <!-- main CSS
		============================================ -->
    <link rel="stylesheet" href="<?= $this->basePath("/vendor/notika/css/main.css"); ?>">
    <!-- style CSS
		============================================ -->
    <link rel="stylesheet" href="<?= $this->basePath("/vendor/notika/style.css"); ?>">
    <!-- responsive CSS
		============================================ -->
    <link rel="stylesheet" href="<?= $this->basePath("/vendor/notika/css/responsive.css"); ?>">
    <link rel="stylesheet" href="<?= $this->basePath("/css/notika/custom.css"); ?>">
    <!-- modernizr JS
		============================================ -->
    <script src="<?= $this->basePath("/vendor/notika/js/vendor/modernizr-2.8.3.min.js"); ?>"></script>
    <style>
        #logo-head {
            color: white;
            font-weight: bold;
            font-size: 1.3rem;
        }

        a.nav-link .spinner4{
            left: 13px;
        }

        a.nav-link .ntd-ctn{
            left: 20px;
        }

        .modal{
          z-index: 9999999;
        }

        ul.notika-main-menu-dropdown li.active a{
            color: #00c292 !important;
            text-decoration: underline;
        }
    </style>
    <?= $this->headLink(); ?>
    <?= $this->headStyle(); ?>
    <script>
      let notifModal,notifModalTitle,notifModalContent;
      let errorModal,errorModalTitle,errorModalContent;
      let loadAJAX = window.XMLHttpRequest.prototype.load;
      window.XMLHttpRequest.prototype.load = function(data){
        console.warn('AJAX LOADED : ', data);
        return loadAJAX.apply(this, arguments);
      };
    </script>
</head>

<body>
    <div id="loaderPage" class="container-fluid hidden"><div id="loaderContent"><div class="loader"></div>PLEASE WAIT</div></div>
    <?php
      $content = $this->content;
      $vars = $this->vars();
      unset($vars['content']);
    ?>
    <!--[if lt IE 8]>
            <p class="browserupgrade">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> to improve your experience.</p>
        <![endif]-->
    <!-- Start Header Top Area -->
    <?= $this->partial('notika/header-top.phtml',[
        'vars'=>$vars
    ]); ?>
    <!-- End Header Top Area -->
    <!-- Mobile Menu start -->
    <?= $this->partial('notika/mobile-menu.phtml',[
        'vars'=>$vars
    ]); ?>
    <!-- Mobile Menu end -->
    <!-- Main Menu area start-->
    <?= $this->partial('notika/main-menu.phtml',[
        'vars'=>$vars
    ]); ?>
    <!-- Main Menu area End-->
    <?php
      $flashMessenger = $this->flashMessenger();
      $flashMessenger->setMessageOpenFormat('<div class="container-fluid" id="alert-container"><div class="alert-list"><div %s role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true"><i class="notika-icon notika-close"></i></span></button>')
          ->setMessageSeparatorString('</div><div %s role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true"><i class="notika-icon notika-close"></i></span></button>')
          ->setMessageCloseString('</div></div></div>');
      // !d($flashMessenger);
        echo $flashMessenger->render('default',['alert', 'alert-dismissible', 'bg-default']);
        echo $flashMessenger->render('error', ['alert', 'alert-dismissible', 'alert-danger']);
        echo $flashMessenger->render('info', ['alert', 'alert-dismissible', 'alert-info']);
        echo $flashMessenger->render('warning', ['alert', 'alert-dismissible', 'alert-warning']);
        echo $flashMessenger->render('success', ['alert', 'alert-dismissible', 'alert-success']);
    ?>

    <div class="container-fluid">
      <?= $content ?>
    </div>
    
    <div class="container">
      <div class="modal fade" id="notifModal" role="dialog">
          <div class="modal-dialog modal-sm bg-default">
              <div class="modal-content bg-default text-white">
                  <div class="modal-header">
                      <button type="button" class="close" data-dismiss="modal">&times;</button>
                  </div>
                  <div class="modal-body">
                      <h2 id="notifModalTitle" class="text-white"><?= _APP_NAME_; ?></h2>
                      <div id="notifModalContent"></div>
                  </div>
              </div>
          </div>
      </div>
        
      <div class="modal fade" id="errorModal" role="dialog">
          <div class="modal-dialog modal-sm modals-default nk-red">
              <div class="modal-content bg-default text-white">
                  <div class="modal-header">
                      <button type="button" class="close" data-dismiss="modal">&times;</button>
                  </div>
                  <div class="modal-body">
                      <h2 id="errorModalTitle" class="text-white"><?= _APP_NAME_; ?></h2>
                      <div id="errorModalContent"></div>
                  </div>
              </div>
          </div>
      </div>
    </div>

    <!-- Start Footer area-->
    <div class="footer-copyright-area">
        <div class="container">
            <div class="row">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="footer-copy-right">
                        <p>
                          Copyright BacangHaneut © 2020 . All rights reserved. 
                          Template by <a href="https://colorlib.com">Colorlib</a>.
                        </p>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- End Footer area-->
    <!-- jquery
		============================================ -->
    <!-- <script src="<?= $this->basePath("/vendor/notika/js/vendor/jquery-1.12.4.min.js"); ?>"></script> -->
    <!-- <script src="<?= $this->basePath("/bower_components/jquery/dist/jquery.min.js"); ?>"></script> -->
    <script src="<?= $this->basePath("/bower_components/jquery2/jquery.min.js"); ?>"></script>
    <script src="<?= $this->basePath("/bower_components/jquery2/jquery-migrate.min.js"); ?>"></script>
    <script src="<?= $this->basePath("/bower_components/sizzle/dist/sizzle.min.js"); ?>"></script>
    <script src="<?= $this->basePath("/bower_components/jquery2/jquery.min.js"); ?>"></script>  
    <!-- bootstrap JS
		============================================ -->
    <script src="<?= $this->basePath("/vendor/notika/js/bootstrap.min.js"); ?>"></script>
    <!-- <script src="<?= $this->basePath("/bower_components/bootstrap4/dist/js/bootstrap.bundle.min.js"); ?>"></script> -->
    <script src="<?= $this->basePath("/bower_components/font-awesome/js/all.min.js"); ?>"></script>
    <!-- wow JS
		============================================ -->
    <!-- <script src="<?= $this->basePath("/vendor/notika/js/wow.min.js"); ?>"></script> -->
    <script src="<?= $this->basePath("/bower_components/wow/dist/wow.min.js"); ?>"></script>
    <!-- price-slider JS
		============================================ -->
    <script src="<?= $this->basePath("/vendor/notika/js/jquery-price-slider.js"); ?>"></script>
    <!-- owl.carousel JS
		============================================ -->
    <!-- <script src="<?= $this->basePath("/vendor/notika/js/owl.carousel.min.js"); ?>"></script> -->
    <script src="<?= $this->basePath("/bower_components/owl.carousel/dist/owl.carousel.min.js"); ?>"></script>
    <!-- scrollUp JS
		============================================ -->
    <script src="<?= $this->basePath("/vendor/notika/js/jquery.scrollUp.min.js"); ?>"></script>
    <!-- meanmenu JS
		============================================ -->
    <script src="<?= $this->basePath("/vendor/notika/js/meanmenu/jquery.meanmenu.js"); ?>"></script>
    <!-- counterup JS
		============================================ -->
    <!-- <script src="<?= $this->basePath("/vendor/notika/js/counterup/jquery.counterup.min.js"); ?>"></script> -->
    <script src="<?= $this->basePath("/bower_components/counterup/jquery.counterup.min.js"); ?>"></script>
    <script src="<?= $this->basePath("/vendor/notika/js/counterup/waypoints.min.js"); ?>"></script>
    <script src="<?= $this->basePath("/vendor/notika/js/counterup/counterup-active.js"); ?>"></script>
    <!-- mCustomScrollbar JS
		============================================ -->
    <script src="<?= $this->basePath("/vendor/notika/js/scrollbar/jquery.mCustomScrollbar.concat.min.js"); ?>"></script>
    <!-- jvectormap JS
		============================================ -->
    <!-- <script src="<?= $this->basePath("/vendor/notika/js/jvectormap/jquery-jvectormap-2.0.2.min.js"); ?>"></script> -->
    <script src="<?= $this->basePath("/bower_components/jvectormap/jquery.jvectormap.min.js"); ?>"></script>
    <script src="<?= $this->basePath("/bower_components/jvectormap/lib/jquery-mousewheel.js"); ?>"></script>
    <script src="<?= $this->basePath("/vendor/notika/js/jvectormap/jquery-jvectormap-world-mill-en.js"); ?>"></script>
    <script src="<?= $this->basePath("/vendor/notika/js/jvectormap/jvectormap-active.js"); ?>"></script>
    <!-- sparkline JS
		============================================ -->
    <script src="<?= $this->basePath("/vendor/notika/js/sparkline/jquery.sparkline.min.js"); ?>"></script>
    <script src="<?= $this->basePath("/vendor/notika/js/sparkline/sparkline-active.js"); ?>"></script>
    <!-- sparkline JS
		============================================ -->
    <script src="<?= $this->basePath("/vendor/notika/js/flot/jquery.flot.js"); ?>"></script>
    <script src="<?= $this->basePath("/vendor/notika/js/flot/jquery.flot.resize.js"); ?>"></script>
    <script src="<?= $this->basePath("/vendor/notika/js/flot/curvedLines.js"); ?>"></script>
    <script src="<?= $this->basePath("/vendor/notika/js/flot/flot-active.js"); ?>"></script>
    <!-- knob JS
		============================================ -->
    <script src="<?= $this->basePath("/vendor/notika/js/knob/jquery.knob.js"); ?>"></script>
    <script src="<?= $this->basePath("/vendor/notika/js/knob/jquery.appear.js"); ?>"></script>
    <script src="<?= $this->basePath("/vendor/notika/js/knob/knob-active.js"); ?>"></script>
    <!-- Input Mask JS
		============================================ -->
    <script src="<?= $this->basePath("/vendor/notika/js/jasny-bootstrap.min.js"); ?>"></script>
    <!-- icheck JS
		============================================ -->
    <script src="<?= $this->basePath("/vendor/notika/js/icheck/icheck.min.js"); ?>"></script>
    <script src="<?= $this->basePath("/vendor/notika/js/icheck/icheck-active.js"); ?>"></script>
    <!-- rangle-slider JS
		============================================ -->
    <script src="<?= $this->basePath("/vendor/notika/js/rangle-slider/jquery-ui-1.10.4.custom.min.js"); ?>"></script>
    <script src="<?= $this->basePath("/vendor/notika/js/rangle-slider/jquery-ui-touch-punch.min.js"); ?>"></script>
    <script src="<?= $this->basePath("/vendor/notika/js/rangle-slider/rangle-active.js"); ?>"></script>
    <!-- datapicker JS
		============================================ -->
    <script src="<?= $this->basePath("/vendor/notika/js/datapicker/bootstrap-datepicker.js"); ?>"></script>
    <script src="<?= $this->basePath("/vendor/notika/js/datapicker/datepicker-active.js"); ?>"></script>
    <!-- bootstrap select JS
		============================================ -->
    <script src="<?= $this->basePath("/vendor/notika/js/bootstrap-select/bootstrap-select.js"); ?>"></script>
    <!--  color-picker JS
		============================================ -->
    <script src="<?= $this->basePath("/vendor/notika/js/color-picker/farbtastic.min.js"); ?>"></script>
    <script src="<?= $this->basePath("/vendor/notika/js/color-picker/color-picker.js"); ?>"></script>
    <!--  notification JS
		============================================ -->
    <script src="<?= $this->basePath("/vendor/notika/js/notification/bootstrap-growl.min.js"); ?>"></script>
    <script src="<?= $this->basePath("/vendor/notika/js/notification/notification-active.js"); ?>"></script>
    <!--  summernote JS
		============================================ -->
    <script src="<?= $this->basePath("/vendor/notika/js/summernote/summernote-updated.min.js"); ?>"></script>
    <script src="<?= $this->basePath("/vendor/notika/js/summernote/summernote-active.js"); ?>"></script>
    <!-- dropzone JS
		============================================ -->
    <script src="<?= $this->basePath("/vendor/notika/js/dropzone/dropzone.js"); ?>"></script>
    <!--  chosen JS
		============================================ -->
    <script src="<?= $this->basePath("/vendor/notika/js/chosen/chosen.jquery.js"); ?>"></script>
    <!--  wave JS
		============================================ -->
    <script src="<?= $this->basePath("/vendor/notika/js/wave/waves.min.js"); ?>"></script>
    <script src="<?= $this->basePath("/vendor/notika/js/wave/wave-active.js"); ?>"></script>
    <!-- autosize JS
		============================================ -->
    <script src="<?= $this->basePath("/vendor/notika/js/autosize.min.js"); ?>"></script>
    <!-- Data Table JS
		============================================ -->
    <!-- <script src="<?= $this->basePath("/vendor/notika/js/data-table/jquery.dataTables.min.js"); ?>"></script> -->
    <script src="<?= $this->basePath("/bower_components/datatables.net/js/jquery.dataTables.min.js"); ?>"></script>
    <!--  todo JS
		============================================ -->
    <script src="<?= $this->basePath("/vendor/notika/js/todo/jquery.todo.js"); ?>"></script>
    <!-- plugins JS
		============================================ -->
    <script src="<?= $this->basePath("/vendor/notika/js/plugins.js"); ?>"></script>
	<!--  Chat JS
		============================================ -->
    <!-- <script src="<?= $this->basePath("/vendor/notika/js/chat/moment.min.js"); ?>"></script> -->
    <script src="<?= $this->basePath("/bower_components/moment/min/moment-with-locales.min.js"); ?>"></script>
    <!-- <script src="<?= $this->basePath("/vendor/notika/js/chat/jquery.chat.js"); ?>"></script> -->
    <!-- main JS
		============================================ -->
    <script src="<?= $this->basePath("/vendor/notika/js/main.js"); ?>"></script>
	<!-- tawk chat JS
		============================================ -->
    <!-- <script src="<?= $this->basePath("/vendor/notika/js/tawk-chat.js"); ?>"></script> -->
    <script>
    // $.fn.selectpicker.Constructor.DEFAULTS.showContent = true;

    function reloadAlert(){
      $.each(unreadalert,function(k,v){
        // console.log(v);
        let html = '<a href="'+v.link+'">'+
            '<div class="hd-message-sn '+v.class+'">'+
                '<div class="hd-message-img">';
        if (v.img!="" && v.img!=null) {
                    html+='<img src="'+v.img+'" alt=""/>';
        }else if(v.icon!="" && v.icon!=null){
                    html+='<i class="'+v.icon+'" style="font-size:2.5rem;padding:0.5rem;"></i>';
        }
                html+='</div>'+
                '<div class="hd-mg-ctn">'+
                    '<h3>'+v.title+'</h3>'+
                    '<p>'+v.content+'</p>'+
                '</div>'+
            '</div>'+
        '</a>';

        alertDOM.prepend(html);
        alertCount++;
      });
      $("#alert-count").html(alertCount);
      setTimeout(reloadAlert,10000);
    }

    function reloadInbox(){
      $.each(unreadinbox,function(k,v){
        // console.log(v);
        let html = '<a href="'+v.link+'">'+
            '<div class="hd-message-sn '+v.class+'">'+
                '<div class="hd-message-img">';
        if (v.img!="" && v.img!=null) {
                    html+='<img src="'+v.img+'" alt=""/>';
        }else if(v.icon!="" && v.icon!=null){
                    html+='<i class="'+v.icon+'" style="font-size:2.5rem;padding:0.5rem;"></i>';
        }
                html+='</div>'+
                '<div class="hd-mg-ctn">'+
                    '<h3>'+v.title+'</h3>'+
                    '<p>'+v.content+'</p>'+
                '</div>'+
            '</div>'+
        '</a>';

        inboxDOM.prepend(html);
        inboxCount++;
      });
      $("#inbox-count").html(inboxCount);
      setTimeout(reloadInbox,10000);
    }

    function showNotifModal(content,title,timeout){
      if(content==undefined)content = "";
      if(title==undefined || title=="")title = "<?= _APP_NAME_; ?>";
      // console.log(content,title,timeout);
      notifModalTitle.html(title);
      notifModalContent.html(content);
      notifModal.modal("show");
      if(timeout!=undefined && timeout>=1000){
        setTimeout(function(){notifModal.modal("hide");},timeout);
      }
    }

  function showErrorModal(content,title,timeout){
    if(content==undefined)content = "";
    if(title==undefined || title=="")title = "<?= _APP_NAME_; ?>";
    // console.log(content,title,timeout);
    errorModalTitle.html(title);
    errorModalContent.html(content);
    errorModal.modal("show");
    if(timeout!=undefined && timeout>=1000){
      setTimeout(function(){errorModal.modal("hide");},timeout);
    }
  }

    function showLoader(){
      $("#loaderPage").fadeIn();
    }

    function hideLoader(){
      $("#loaderPage").hide();
    }

    $(document).ready(function(){
      // hideLoader();
      notifModal = $("#notifModal");
      notifModalTitle = $("#notifModalTitle");
      notifModalContent = $("#notifModalContent");
      errorModal = $("#errorModal");
      errorModalTitle = $("#errorModalTitle");
      errorModalContent = $("#errorModalContent");
      inboxDOM = $("#inbox-notif");
      alertDOM = $("#alert-notif");
      $(".notika-menu-wrap li a").on("click",function(){
          $(".notika-menu-wrap li a.active").removeClass("active");
          $(".notika-menu-wrap li.active").removeClass("active");
          $(".tab-content.custom-menu-content .tab-pane.active").removeClass("active");
          const aDOM = $(this).addClass("active");
          let id = $(this).data('target');
          // console.log(id);
          const liDOM = $(this).parent().addClass("active");
          $(".tab-content.custom-menu-content "+id).addClass("active");
      });

      setTimeout(reloadInbox,10000);
      setTimeout(reloadAlert,10000);
      setTimeout(function(){hideLoader()},500);
      // setTimeout(function(){if($("#alert-container").length>0)$("#alert-container").slideUp()},10000);
    });
    </script>

    <?= $this->headScript()?>
    
    <?= $this->inlineScript() ?>
</body>

</html>