<html>

<head>
    <meta charset="UTF-8">
    <meta name="apple-mobile-web-app-title" content="Z3">
    <title><?= _APP_NAME_; ?> - SignIn</title>
    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:200,300" rel="stylesheet">
    <style>
        * {
            box-sizing: border-box;
            margin: 0;
            padding: 0;
            font-weight: 300;
        }

        body {
            font-family: 'Source Sans Pro', sans-serif;
            color: white;
            font-weight: 300;
        }

        body ::-webkit-input-placeholder {
            /* WebKit browsers */
            font-family: 'Source Sans Pro', sans-serif;
            color: white;
            font-weight: 300;
        }

        body :-moz-placeholder {
            /* Mozilla Firefox 4 to 18 */
            font-family: 'Source Sans Pro', sans-serif;
            color: white;
            opacity: 1;
            font-weight: 300;
        }

        body ::-moz-placeholder {
            /* Mozilla Firefox 19+ */
            font-family: 'Source Sans Pro', sans-serif;
            color: white;
            opacity: 1;
            font-weight: 300;
        }

        body :-ms-input-placeholder {
            /* Internet Explorer 10+ */
            font-family: 'Source Sans Pro', sans-serif;
            color: white;
            font-weight: 300;
        }

        .wrapper {
            background: #00c292;
            background: linear-gradient(to bottom right, #00c292 0%, #abffeb 100%);
            position: absolute;
            /* top: 50%; */
            left: 0;
            width: 100%;
            height: 100%;
            /* margin-top: -200px; */
            overflow: hidden;
            padding-top:5rem;
        }

        .wrapper.form-success .container h1 {
            -webkit-transform: translateY(85px);
            transform: translateY(85px);
        }

        .container {
            max-width: 600px;
            margin: 0 auto;
            padding: 80px 0;
            height: 400px;
            text-align: center;
        }

        .container h1 {
            font-size: 40px;
            transition-duration: 1s;
            transition-timing-function: ease-in-put;
            font-weight: 200;
        }

        form {
            padding: 20px 0;
            position: relative;
            z-index: 2;
        }

        form input:not([type='checkbox']) {
            -webkit-appearance: none;
            -moz-appearance: none;
            appearance: none;
            outline: 0;
            border: 1px solid rgba(255, 255, 255, 0.4);
            background-color: rgba(255, 255, 255, 0.2);
            width: 250px;
            border-radius: 3px;
            padding: 10px 15px;
            margin: 0 auto 10px auto;
            display: block;
            text-align: center;
            font-size: 18px;
            color: white;
            transition-duration: 0.25s;
            font-weight: 300;
        }

        form input:not([type='checkbox']):hover {
            background-color: rgba(255, 255, 255, 0.4);
        }

        form input:not([type='checkbox']):focus {
            background-color: white;
            width: 300px;
            color: #00c292;
        }

        form button {
            -webkit-appearance: none;
            -moz-appearance: none;
            appearance: none;
            outline: 0;
            background-color: white;
            border: 0;
            padding: 10px 15px;
            color: #00c292;
            border-radius: 3px;
            width: 250px;
            cursor: pointer;
            font-size: 18px;
            transition-duration: 0.25s;
        }

        form button:hover {
            background-color: #f5f7f9;
        }

        .bg-bubbles {
            position: absolute;
            top: 0;
            left: 0;
            width: 100%;
            height: 100%;
            z-index: 1;
        }

        .bg-bubbles li {
            position: absolute;
            list-style: none;
            display: block;
            width: 40px;
            height: 40px;
            background-color: rgba(255, 255, 255, 0.15);
            bottom: -160px;
            -webkit-animation: square 25s infinite;
            animation: square 25s infinite;
            transition-timing-function: linear;
        }

        .bg-bubbles li:nth-child(1) {
            left: 10%;
        }

        .bg-bubbles li:nth-child(2) {
            left: 20%;
            width: 80px;
            height: 80px;
            -webkit-animation-delay: 2s;
            animation-delay: 2s;
            -webkit-animation-duration: 17s;
            animation-duration: 17s;
        }

        .bg-bubbles li:nth-child(3) {
            left: 25%;
            -webkit-animation-delay: 4s;
            animation-delay: 4s;
        }

        .bg-bubbles li:nth-child(4) {
            left: 40%;
            width: 60px;
            height: 60px;
            -webkit-animation-duration: 22s;
            animation-duration: 22s;
            background-color: rgba(255, 255, 255, 0.25);
        }

        .bg-bubbles li:nth-child(5) {
            left: 70%;
        }

        .bg-bubbles li:nth-child(6) {
            left: 80%;
            width: 120px;
            height: 120px;
            -webkit-animation-delay: 3s;
            animation-delay: 3s;
            background-color: rgba(255, 255, 255, 0.2);
        }

        .bg-bubbles li:nth-child(7) {
            left: 32%;
            width: 160px;
            height: 160px;
            -webkit-animation-delay: 7s;
            animation-delay: 7s;
        }

        .bg-bubbles li:nth-child(8) {
            left: 55%;
            width: 20px;
            height: 20px;
            -webkit-animation-delay: 15s;
            animation-delay: 15s;
            -webkit-animation-duration: 40s;
            animation-duration: 40s;
        }

        .bg-bubbles li:nth-child(9) {
            left: 25%;
            width: 10px;
            height: 10px;
            -webkit-animation-delay: 2s;
            animation-delay: 2s;
            -webkit-animation-duration: 40s;
            animation-duration: 40s;
            background-color: rgba(255, 255, 255, 0.3);
        }

        .bg-bubbles li:nth-child(10) {
            left: 90%;
            width: 160px;
            height: 160px;
            -webkit-animation-delay: 11s;
            animation-delay: 11s;
        }

        @-webkit-keyframes square {
            0% {
                -webkit-transform: translateY(0);
                transform: translateY(0);
            }

            100% {
                -webkit-transform: translateY(-700px) rotate(600deg);
                transform: translateY(-700px) rotate(600deg);
            }
        }

        @keyframes square {
            0% {
                -webkit-transform: translateY(0);
                transform: translateY(0);
            }

            100% {
                -webkit-transform: translateY(-700px) rotate(600deg);
                transform: translateY(-700px) rotate(600deg);
            }
        }

        #wait-text{
            font-size: 1rem;
        }

        .badge-danger{
            background-color: darkred;
            padding: 1px 5px;
        }
    </style>
</head>

<body>
    <?php 
    //!d($this->try,$this->wait); 
    ?>
    <div class="wrapper">
        <div class="container">
            <?php if($this->wait>0){ ?>
            <h1>
                <a href="<?= $this->basePath("/"); ?>" 
                style="color:white;text-decoration:none;font-weight:bold;position:relative;z-index:2"><?= _APP_ALIAS_; ?></a> APP
                <br>
            </h1>
            <span id="wait-text">please try again after <span id="wait-time"><?= $this->wait; ?></span> <?=(($this->wait>1)?'seconds':'second'); ?></span>
            <?php }else{ ?>
            <h1>
                <a href="<?= $this->basePath("/"); ?>" 
                style="color:white;text-decoration:none;font-weight:bold;position:relative;z-index:2"><?= _APP_ALIAS_; ?></a> APP
                <br><span id="wait-text"><?= $this->msg; ?></span>
            </h1>
            <form class="form validate-form" method="post">
                <input type="text" placeholder="Username" name="username">
                <input type="password" placeholder="Password" name="password">
                <div><input type="checkbox" name="remember_me"> Remember Me</div><br>
                <?= $this->formElement($form->get('redirect_url')); ?>
                <?= $this->formElement($form->get('csrf')) ?>
                <button type="submit" id="login-button">Login</button>
            </form>
            <?php } ?>
        </div>
        <ul class="bg-bubbles">
            <li></li>
            <li></li>
            <li></li>
            <li></li>
            <li></li>
            <li></li>
            <li></li>
            <li></li>
            <li></li>
            <li></li>
        </ul>
    </div>
	<script src="<?= $this->basePath("/vendor/jQuery/jquery-3.4.1.min.js"); ?>"></script>
    <script>
        $(document).ready(function(){
            <?php
                if($this->isLoginError){
            ?>
                $("#wait-text").addClass("badge-danger");
            <?php
                }
            ?>
            let time = $("#wait-time").html();
            if(time!=undefined){
                setInterval(function(){
                    time--;
                    if(time<=1){
                        setTimeout(function(){
                            this.document.location.href = "<?= $this->url('app/auth',['action'=>"login"]); ?>";
                        },1000);
                    }else{
                        $("#wait-time").html(time);
                    }
                },1000);
            }
            
            $("#login-button").click(function (event) {
                event.preventDefault();
                $('form').hide();
                $("#wait-text").removeClass("badge-danger");
                $("#wait-text").html("please wait...");

                $('.wrapper').addClass('form-success');
                setTimeout(function(){
                    $('form').submit();
                },1000);
            });
        });
    </script>
</body>

</html>